BinaryWeatherApp/Entities/WeatherContext.cs
using BinaryWeatherApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace BinaryWeatherApp.Entities
{
	public class WeatherContext : DbContext
	{
		public WeatherContext(string connectionString) : base (connectionString)
		{

		}

		public DbSet<Town> Towns { get; set; }
		public DbSet<Request> Requests { get; set; }
	}

	public class DbInitializer : DropCreateDatabaseIfModelChanges<WeatherContext>
	{
		protected override void Seed(WeatherContext db)
		{
			db.Towns.Add(new Town { TownName = "Kiev" });
			db.Towns.Add(new Town { TownName = "Lviv" });
			db.Towns.Add(new Town { TownName = "Kharkiv" });
			db.Towns.Add(new Town { TownName = "Dnipropetrovsk" });
			db.Towns.Add(new Town { TownName = "Odessa" });

			db.SaveChanges();
		}
	}
}

BinaryWeatherApp/Models/Request.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace BinaryWeatherApp.Models
{
	public class Request
	{
		public int RequestId { get; set; }
		public string RequestTown { get; set; }
		public string RequestDate { get; set; }
		public int RequestDays { get; set; }
		public double RequestTemp { get; set; }
		public string RequestImg { get; set; }
	}
}

BinaryWeatherApp/Models/Town.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace BinaryWeatherApp.Models
{
	public class Town
	{
		public int TownId { get; set; }
		public string TownName { get; set; }
	}
}

BinaryWeatherApp/Models/Weather.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BinaryWeatherApp.Models
{
	public class Coord
	{
		public double lon { get; set; }
		public double lat { get; set; }
	}

	public class City
	{
		public int id { get; set; }
		public string name { get; set; }
		public Coord coord { get; set; }
		public string country { get; set; }
		public int population { get; set; }
	}

	public class Temp
	{
		public double day { get; set; }
		public double min { get; set; }
		public double max { get; set; }
		public double night { get; set; }
		public double eve { get; set; }
		public double morn { get; set; }
	}

	public class Weather
	{
		public int id { get; set; }
		public string main { get; set; }
		public string description { get; set; }
		public string icon { get; set; }
	}

	public class List
	{
		public int dt { get; set; }
		public Temp temp { get; set; }
		public double pressure { get; set; }
		public int humidity { get; set; }
		public List<Weather> weather { get; set; }
		public double speed { get; set; }
		public int deg { get; set; }
		public int clouds { get; set; }
		public double? rain { get; set; }
	}

	public class RootObject
	{
		public City city { get; set; }
		public string cod { get; set; }
		public double message { get; set; }
		public int cnt { get; set; }
		public List<List> list { get; set; }
	}
	public class DailyForecast
	{
		public double morning { get; set; }
		public double day { get; set; }
		public double evening { get; set; }
		public double night { get; set; }
		public bool rain { get; set; }
		public double pressure { get; set; }
		public double humidity { get; set; }
		public string icon { get; set; }
		public string date { get; set; }
	}
	public class Forecast
	{
		public List<DailyForecast> forecast { get; private set; }
		public string city { get; private set; }

		public Forecast(RootObject obj)
		{
			forecast = new List<DailyForecast>();
			city = obj.city.name;
			int i = 0;
			foreach (var x in obj.list)
			{
				DailyForecast dayF = new DailyForecast()
				{
					day = x.temp.day,
					morning = x.temp.morn,
					evening = x.temp.eve,
					night = x.temp.night,
					rain = x.rain > 0.5,
					pressure = x.pressure,
					humidity = x.humidity,
					icon = $"http://openweathermap.org/img/w/{x.weather.FirstOrDefault().icon}.png",
					date = DateTime.Now.AddDays(i++).ToShortDateString()
				};
				forecast.Add(dayF);
			}
		}

		public List<DailyForecast> GetDailyList()
		{
			return forecast;
		}
	}
}

BinaryWeatherApp/Controllers/HomeController.cs
using BinaryWeatherApp.Entities;
using BinaryWeatherApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BinaryWeatherApp.Controllers
{
	public class HomeController : Controller
	{

		public ActionResult Index()
		{
			return RedirectToAction("Index", "Weather");
		}
	}
}

BinaryWeatherApp/Controllers/RequestsController.cs
using BinaryWeatherApp.Models;
using BinaryWeatherApp.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BinaryWeatherApp.Controllers
{
	public class RequestsController : Controller
	{
		IUnitOfWork unitOfWork;
		public RequestsController(IUnitOfWork iuow)
		{
			unitOfWork = iuow;
		}
		public async Task<ActionResult> Index()
		{
			var requests =(await unitOfWork.Requests.GetAllAsync()).OrderByDescending(x => x.RequestId).Take(10).ToList<Request>();
			return View(requests);
		}
	}
}

BinaryWeatherApp/Controllers/TownsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BinaryWeatherApp.Repositories;
using BinaryWeatherApp.Models;
using System.Threading.Tasks;

namespace BinaryWeatherApp.Controllers
{
	public class TownsController : Controller
	{
		IUnitOfWork unitOfWork;
		public TownsController(IUnitOfWork itr)
		{
			unitOfWork = itr;
		}
		public async Task<ActionResult> Index()
		{
			var towns = await unitOfWork.Towns.GetAllAsync();
			return View(towns);
		}
		[HttpGet]
		public ActionResult Create()
		{
			return View();
		}

		[HttpGet]
		public async Task<ActionResult> Edit (int id)
		{
			var town = await unitOfWork.Towns.GetByIdAsync(id);
			return View(town);
		}

		[HttpPost]
		public async Task<ActionResult> Create(Town item)
		{
			if (ModelState.IsValid && !string.IsNullOrWhiteSpace(item.TownName))
			{
				Town town = new Town()
				{
					TownName = item.TownName
				};
				await unitOfWork.Towns.CreateAsync(town);
				return RedirectToAction("Index");
			}
			else
			{
				return View(item);
			}
		}
		
		[HttpPost]
		public async Task<ActionResult> Edit(Town item)
		{
			if (ModelState.IsValid && !string.IsNullOrWhiteSpace(item.TownName))
			{
				await unitOfWork.Towns.EditAsync(item);
				return RedirectToAction("Index");
			}
			else
			{
				return View(item);
			}
		}
		public async Task<ActionResult> Delete(int id)
		{
			await unitOfWork.Towns.DeleteAsync(id);
			return RedirectToAction("Index");
		}
	}
}

BinaryWeatherApp/Controllers/WeatherController.cs
using BinaryWeatherApp.Models;
using BinaryWeatherApp.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ninject;
using BinaryWeatherApp.Repositories;
using System.Threading.Tasks;

namespace BinaryWeatherApp.Controllers
{
	public class WeatherController : Controller
	{
		IWeatherService weatherService;
		IUnitOfWork unitOfWork;
		

		public WeatherController(IWeatherService iws, IUnitOfWork iuow)
		{
			weatherService = iws;
			unitOfWork = iuow;
           
		}
		public async Task<ActionResult> Index()
		{
            var towns = await  unitOfWork.Towns.GetAllAsync();

            ViewBag.Towns = towns;
            return View();
		}

		[HttpPost]
		public async Task<ActionResult> Index(string city, int days)
		{
            var towns = await unitOfWork.Towns.GetAllAsync();

            ViewBag.Towns = towns;
            if (!string.IsNullOrWhiteSpace(city))
			{
				Forecast forecast = await weatherService.Get(city, days);
				Request request = new Request
				{
					RequestTown = forecast.city,
					RequestDays = days,
					RequestDate = forecast.GetDailyList()[0].date,
					RequestImg = forecast.GetDailyList()[0].icon,
					RequestTemp = forecast.GetDailyList()[0].day 
				};
				await unitOfWork.Requests.CreateAsync(request);
				return View(forecast);
			}
			return View();
		}
	}
}

BinaryWeatherApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BinaryWeatherApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BinaryWeatherApp/Views/Home/Index.cshtml
@model IEnumerable<BinaryWeatherApp.Models.Town>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div>
        <h3>Распродажа книг</h3>
        <table>
            <tr class="header"><td><p>Название книги</p></td>
                <td><p>Автор</p></td>
                <td><p>Цена</p></td><td></td>
            </tr>
            @foreach (BinaryWeatherApp.Models.Town b in Model)
            {
            <tr>
                <td><p>@b.TownId</p></td>				
                <td><p>@b.TownName</p></td>
                <td><p><a href="/Home/Buy/@b.TownId">Купить</a></p></td>
            </tr>
            }
        </table>
    </div>

BinaryWeatherApp/Views/Requests/Index.cshtml
@model List<BinaryWeatherApp.Models.Request>

@{
	ViewBag.Title = "View";
}
<style type="text/css">
table {
		color: #4F4B79;
	}

	td {
		background: /*#5BF0E8*/ #56DED7;
		font-family: Century;
	}
</style>
<h2>Your Last Requests</h2>

<table class="table">
	<tr>
		<th>
			City Name
		</th>
		<th>
			Request Date
		</th>
		<th>
			Number of Days
		</th>
		<th>
			Temperature
		</th>
		<th>
			Weather
		</th>
		<th></th>
	</tr>

@foreach (var item in Model) {
	<tr>
		<td>
			@Html.DisplayFor(modelItem => item.RequestTown)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.RequestDate)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.RequestDays)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.RequestTemp)
		</td>
		<td>
			<img src="@item.RequestImg" height="50" width="50">
		</td>
	</tr>
}

</table>
<h4 align="center"> @Html.ActionLink("Back","Index","Weather") </h4>

BinaryWeatherApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="~/Content/CustomStyle.css" />
	<title>@ViewBag.Title</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	<style>
		a {
			/*color: #4A60CE;*/
			color: #18AAD0;
		}

		a:hover {
				text-decoration: none;
			}
		body {
			background: #A9E2F3;
		}
	</style>

</head>

<body class="body_style">
	<header class="header_container">
	<div class="header_home_link">
		<a href='@Url.Action("Index", "Weather")' class="link">
			<img src="~/Content/Icons/weather-icon.png" height="60" width="60" />
		</a>
	</div>
	<div class="header_links">
		<div class="header_link">
			<a href='@Url.Action("Index", "Weather")' class="link" data-content="Home">
				<img src="~/Content/Icons/home-icon.png" height="40" width="40" />
				<br/> Home </a>
		</div>
		<div class="header_link">
			<a href='@Url.Action("Index", "Requests")' class="link">
				<img src="~/Content/Icons/requests-icon.png" height="40" width="40" />
				<br /> Requests </a>
		</div>
		<div class="header_link" >
			<a href='@Url.Action("Index", "Towns")' class="link">
				<img src="~/Content/Icons/town-icon.png" height="40" width="40" />
				<br /> Towns </a>
		</div>
	</div>
</header>
	<hr/>
	<main>
		@RenderBody()
	</main>
	<footer class=" footer">
		<div class="footer_elem">
			<p>Weather Forecast</p>
			<p>In any city of the planet</p>
		</div>
		<div class="footer_elem">
			<p>Kharkiv, Ukraine</p>
			<p>+8-800-555-3535</p>
		</div>
	</footer>
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>

BinaryWeatherApp/Views/Towns/Create.cshtml
@model BinaryWeatherApp.Models.Town

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Town</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TownName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TownName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TownName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BinaryWeatherApp/Views/Towns/Edit.cshtml
@model BinaryWeatherApp.Models.Town

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Town</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TownId)

        <div class="form-group">
            @Html.LabelFor(model => model.TownName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TownName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TownName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BinaryWeatherApp/Views/Towns/Index.cshtml
@model List<BinaryWeatherApp.Models.Town>

@{
    ViewBag.Title = "Index";
}

<h2>Favorite Towns</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TownName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TownId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TownId })
        </td>
    </tr>
}

</table>
<h4 align="center"> @Html.ActionLink("Back", "Index", "Weather") </h4>

BinaryWeatherApp/Views/Towns/View.cshtml
@model BinaryWeatherApp.Models.Town

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Town</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TownId)

        <div class="form-group">
            @Html.LabelFor(model => model.TownName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TownName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TownName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BinaryWeatherApp/Views/Weather/Index.cshtml
@model BinaryWeatherApp.Models.Forecast
@{
	ViewBag.Title = "Weather";
}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />

</head>

<body align="center">
		@using (Html.BeginForm("Index", "Weather", FormMethod.Post))
		{

			var towns = new List<SelectListItem>();
			if (ViewBag.Towns != null)
			{
				foreach (BinaryWeatherApp.Models.Town x in ViewBag.Towns)
				{
					towns.Add(new SelectListItem() { Text = x.TownName, Value = x.TownName });
				}
			}
			<p>@Html.DropDownList("city", towns, new { @class = "btn btn-default dropdown-toggle" }) @Html.RadioButton("city", "")  Favorites </p>
			<p>
				@Html.TextBox("city"@*, new { @class = "form-control" }*@) @Html.RadioButton("city", "", false) Other City

			</p>
			<br />

			<p>
				You want a forecast for
				@Html.DropDownList("days", new List<SelectListItem>
	  { new SelectListItem{ Text = "1 Day", Value = "1"},
	  new SelectListItem{ Text = "3 Days", Value = "3"},
	  new SelectListItem{ Text = "7 Days", Value = "7"}}, new { @class = "btn btn-default dropdown-toggle" })
			</p>
			<input type="submit" value="Get" />
		}
		@Html.Partial("Result", Model)
</body>
</html>

BinaryWeatherApp/Views/Weather/Result.cshtml
@model BinaryWeatherApp.Models.Forecast
	
<style type="text/css">
	table {
		color: #4F4B79;
		background: /*#5BF0E8*/ #56DED7;
		font-family: Century;
	}
</style>
<body>

	@if (Model != null)
	{
		<hr />
		<p><strong> Weather in @Model.city: </strong></p>


		<table class="table-bordered" align="center">
			<tr>
				<td>Date</td>
				<td> <div class="table_item" align="center"> Morning </div> </td>
				<td class="table_item" align="center"> Afternoon </td>
				<td class="table_item" align="center"> Evening </td>
				<td class="table_item" align="center"> Night </td>
				<td class="table_item" align="center"> Humidity </td>
				<td class="table_item" align="center"> Pressure </td>
				<td ></td>
			</tr>
			@foreach (var x in Model.GetDailyList())
			{
				<tr>
					<td class="table_item" align="center"> @x.date </td>
					<td class="table_item" align="center"> @x.morning °C </td>
					<td class="table_item"align="center"> @x.day °C </td>
					<td class="table_item" align="center"> @x.evening °C </td>
					<td class="table_item" align="center"> @x.night °C </td>
					<td class="table_item" align="center">@x.humidity %</td>
					<td class="table_item" align="center"> @x.pressure hPa </td>
					<td><img src="@x.icon" height="50" width="50"></td>
				</tr>
			}
		</table>
	}
</body>